import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
	title: 'Minesweeper',
	description: 'Generated by create next app',
}

const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={roboto.className}>
			<body>{children}</body>
		</html>
	)
}
